cou_site/controllers/__init__.py
from flask import Blueprint, render_template, abort, redirect, url_for
from sqlalchemy.orm.exc import NoResultFound

from cou_site.controllers.team import developers
from cou_site.models.post import Post


core_pages = Blueprint("core_pages", __name__)


@core_pages.route("/")
def _index():
    latest_post = (
        Post.query.filter(Post.is_blog_post)
        .order_by(Post.created.desc())
        .limit(1)
        .one()
    )
    return render_template("index.html", latest_post=latest_post)


@core_pages.route("/about")
def _about():
    return render_template("about.html", team=developers)


@core_pages.route("/about/features")
def _features():
    return render_template("features.html")


@core_pages.route("/fine-print")
def _fine_print():
    return render_template("fine_print.html")


@core_pages.route("/help")
def _help():
    return render_template("help.html")


@core_pages.route("/login")
def _login():
    return render_template("login.html")


@core_pages.route("/edit/<post_id>")
def edit_post(post_id):
    if not str.isdigit(post_id):
        return abort(404)

    try:
        post = Post.query.filter(Post.entry_id == post_id).one()
    except NoResultFound:
        return abort(404)

    return render_template("edit.html", mode="post", entry=post, category=post.category)

cou_site/controllers/api/auth.py
import json

from flask import Blueprint, request, session, redirect

from cou_site.config import game_server_uri
from cou_site.controllers.api import respond
from cou_site.models.user import User

AUTH_SERVER = f"{game_server_uri}:8383/auth"
auth = Blueprint("auth", __name__, url_prefix="/api/auth")


@auth.route("/login", methods=["POST"])
def login_api():
    if not request.data:
        return respond(False, "missing login data"), 400

    session["auth"] = json.loads(request.data)
    session["user_id"] = (
        User.query.filter(User.email == session["auth"]["playerEmail"]).one()
    ).user_id
    return respond()


@auth.route("/logout")
def logout_api():
    session.pop("auth")
    session.pop("user_id")
    return redirect(request.referrer)

cou_site/controllers/encyclopedia/__init__.py
from flask import Blueprint, render_template, request, abort

from cou_site.config import game_server_uri as server, rs_token
from cou_site.controllers.encyclopedia.cache import (
    CategorizedCachedJSONResource,
    CachedEntitiesResource,
    CachedLocationsResource,
    CachedConnectingStreetsList,
    CachedJSONResource,
)
from cou_site.controllers.encyclopedia.search import search_data
from cou_site.models.encyclopedia.achievement import (
    Achievement,
    CATEGORIES as ACHIEVEMENT_CATEGORIES,
    PATH as ACHIEVEMENT_PATH,
)
from cou_site.models.encyclopedia.giants import GIANTS, PATH as GIANT_PATH
from cou_site.models.encyclopedia.item import (
    Item,
    CATEGORIES as ITEM_CATEGORIES,
    PATH as ITEM_PATH,
)
from cou_site.models.encyclopedia.location import PATH as LOCATION_PATH
from cou_site.models.encyclopedia.skill import (
    Skill,
    CATEGORIES as SKILL_CATEGORIES,
    PATH as SKILL_PATH,
)
from cou_site.controllers.util import split_camel_case

encyclopedia = Blueprint("encyclopedia", __name__, url_prefix="/encyclopedia")

entities = CachedEntitiesResource(f"{server}/entities/list?token={rs_token}")
skills = CategorizedCachedJSONResource(
    url=f"{server}/skills/list?token={rs_token}",
    dict_parser=Skill.from_dict,
    categories=SKILL_CATEGORIES,
)
achievements = CategorizedCachedJSONResource(
    url=f"{server}/listAchievements?token={rs_token}",
    dict_parser=Achievement.from_dict,
    categories=ACHIEVEMENT_CATEGORIES,
)
locations = CachedLocationsResource(f"{server}/getMapData?token={rs_token}")
items = CategorizedCachedJSONResource(
    url=f"{server}/getItems", dict_parser=Item.from_dict, categories=ITEM_CATEGORIES
)
world_graph = CachedJSONResource(f"file://worldGraph.json")


@encyclopedia.context_processor
def _inject_context():
    def sanitize_category(category_name: str) -> str:
        return category_name.replace(" ", "").replace("&", "").lower()

    return dict(
        # For example: locations
        current_section=request.path.split("/")[2],
        sanitize_category=sanitize_category,
    )


@encyclopedia.route("/")
def _index():
    return render_template("encyclopedia/index.html")


@encyclopedia.route("/search")
def _search():
    query = request.args.get("q", str())

    if not query:
        return abort(400)

    results = {
        "Achievements": search_data(query, achievements.data.by_id.values()),
        "Entities": search_data(query, entities.data.values()),
        "Items": search_data(query, items.data.by_id.values()),
        "Locations": search_data(
            query,
            set(locations.data.streets.values()) | set(locations.data.hubs.values()),
        ),
        "Giants": search_data(query, GIANTS.values()),
        "Skills": search_data(query, skills.data.by_id.values()),
    }

    have_results = False
    for result_list in results.values():
        if result_list:
            have_results = True
            break

    return render_template(
        "encyclopedia/search.html",
        query=query,
        results=results,
        have_results=have_results,
    )


@encyclopedia.route(f"/{ACHIEVEMENT_PATH}/")
def _achv_index():
    return render_template(
        "encyclopedia/categorical_list.html",
        list_title="Achievements",
        list_objs=achievements.data.by_cat,
    )


@encyclopedia.route(f"/{ACHIEVEMENT_PATH}/<achv_id>")
def _achv(achv_id: str):
    achievements_by_id = achievements.data.by_id

    if achv_id not in achievements_by_id:
        return abort(404)

    return render_template(
        "encyclopedia/categorical_object.html",
        path=ACHIEVEMENT_PATH,
        obj=achievements_by_id[achv_id],
    )


@encyclopedia.route("/entities/")
def _entities_index():
    return render_template(
        "encyclopedia/list.html",
        list_title="Entities",
        list_objs=entities.data.values(),
    )


@encyclopedia.route(f"/{ITEM_PATH}/")
def _items_index():
    return render_template(
        "encyclopedia/categorical_list.html",
        list_title="Items",
        list_objs=items.data.by_cat,
    )


@encyclopedia.route(f"/{ITEM_PATH}/<item_id>")
def _item(item_id: str):
    items_by_id = items.data.by_id

    if item_id not in items_by_id:
        return abort(404)

    return render_template(
        "encyclopedia/categorical_object.html",
        path=ITEM_PATH,
        obj=items_by_id[item_id],
        item=True,
    )


@encyclopedia.route(f"/{LOCATION_PATH}/")
def _locations_index():
    return render_template(
        "encyclopedia/locations.html",
        hubs=locations.data.hubs.values(),
        streets=locations.data.streets.values(),
    )


@encyclopedia.route(f"/{LOCATION_PATH}/<loc_id>")
def _location(loc_id: str):
    hubs, streets = locations.data

    if loc_id in hubs.keys():
        hub = hubs[loc_id]
        return render_template("encyclopedia/hub.html", hub=hub)
    elif loc_id in streets.keys():
        street = streets[loc_id]

        if not street.connections:
            street.connections = CachedConnectingStreetsList(
                street, locations, world_graph
            )

        return render_template(
            "encyclopedia/street.html",
            street=street,
            hub=hubs[street.category],
            split_camel_case=split_camel_case,
        )
    else:
        return abort(404)


@encyclopedia.route(f"/{GIANT_PATH}/")
def _giants_index():
    return render_template(
        "encyclopedia/list.html", list_title="Giants", list_objs=GIANTS.values()
    )


@encyclopedia.route(f"/{GIANT_PATH}/<giant_id>")
def _giant(giant_id: str):
    if giant_id not in GIANTS:
        return abort(404)

    return render_template("encyclopedia/giant.html", giant=GIANTS[giant_id])


@encyclopedia.route(f"/{SKILL_PATH}/")
def _skills_index():
    return render_template(
        "encyclopedia/categorical_list.html",
        list_title="Skills",
        list_objs=skills.data.by_cat,
    )


@encyclopedia.route(f"/{SKILL_PATH}/<skill_id>")
def _skill(skill_id: str):
    skills_by_id = skills.data.by_id

    if skill_id not in skills_by_id:
        return abort(404)

    return render_template(
        "encyclopedia/skill.html", skill=skills_by_id[skill_id], giants=GIANTS
    )

cou_site/templates/_common/encyclopedia_nav.html
<ul class="nav nav-tabs nav-justified">
    <li class="{{ 'active' if current_section == 'achievements' }}">
        <a href="{{ url_for('encyclopedia._achv_index') }}">
            <img src="{{ url_for('static', filename='img/encyclopedia/achievements.png') }}" alt="">
            <p class="lead">Achievements</p>
        </a>
    </li>
    <li class="{{ 'active' if current_section == 'entities' }}">
        <a href="{{ url_for('encyclopedia._entities_index') }}">
            <img src="{{ url_for('static', filename='img/encyclopedia/entities.png') }}" alt="">
            <p class="lead">Entities</p>
        </a>
    </li>
    <li class="{{ 'active' if current_section == 'items' }}">
        <a href="{{ url_for('encyclopedia._items_index') }}">
            <img src="{{ url_for('static', filename='img/encyclopedia/items.png') }}" alt="">
            <p class="lead">Items</p>
        </a>
    </li>
    <li class="{{ 'active' if current_section == 'locations' }}">
        <a href="{{ url_for('encyclopedia._locations_index') }}">
            <img src="{{ url_for('static', filename='img/encyclopedia/locations.png') }}" alt="">
            <p class="lead">Locations</p>
        </a>
    </li>
    <li class="{{ 'active' if current_section == 'giants' }}">
        <a href="{{ url_for('encyclopedia._giants_index') }}">
            <img src="{{ url_for('static', filename='img/encyclopedia/giants.png') }}" alt="">
            <p class="lead">Giants</p>
        </a>
    </li>
    <li class="{{ 'active' if current_section == 'skills' }}">
        <a href="{{ url_for('encyclopedia._skills_index') }}">
            <img src="{{ url_for('static', filename='img/encyclopedia/skills.png') }}" alt="">
            <p class="lead">Skills</p>
        </a>
    </li>
</ul>
<br>

cou_site/templates/_common/foot.html
<!-- Footer -->
<div class="footer navbar-default navbar-static-top">
    <div class="container{{ '-fluid' if fluid }}">
        <p class="navbar-text navbar-left">
            &copy; 2013 - {{ year }} Children of Ur <span class="hidden-xs">Development Team</span> - <a
                style="cursor: pointer;" type="button" id="disclaimer" class="navbar-link link" rel="popover"
                data-toggle="popover">Disclaimer</a>
        <noscript>:
            <small>Children of Ur is not endorsed or affiliated with <a href="http://tinyspeck.com" target="_blank">Tiny
                Speck</a> (the original developers of <a href="http://glitchthegame.com/" target="_blank">Glitch</a>) in
                any way. Enable JavaScript to hide this message.
            </small>
        </noscript>
        </p>
    </div>
</div>

<!-- Scripts -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script>
    $('#disclaimer').popover({
        'placement': 'top',
        'title': 'Disclaimer <button onclick="$(&quot;#disclaimer&quot;).popover(&quot;hide&quot;);" class="pull-right close" data-dismiss="popover" style="margin-top: -2px;">&times;</button>',
        'content': 'Children of Ur is not endorsed or affiliated with <a href="http://tinyspeck.com" target="_blank">Tiny Speck</a> (the original developers of <a href="http://glitchthegame.com/" target="_blank">Glitch</a>) in any way.',
        'html': 'true',
        'trigger': 'click manual'
    });
</script>

cou_site/templates/_common/head.html
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">

<meta name="description" content="A community remake of Glitch™ - A Game of Giant Imagination"/>
<meta name="keywords"
      content="Children of Ur, CoU, community, remake, Glitch, Glitch the Game, Ur, Eleven, Giant, Giant Imagination, imagination"/>
<link rel="icon" href="{{ url_for('static', filename='img/logo/favicon.ico') }}">
<link rel="shortcut icon" href="{{ url_for('static', filename='img/logo/favicon.png') }}">

<!-- Fonts -->
<link href="https://fonts.googleapis.com/css?family=Arvo|Source+Code+Pro:400,700|Varela+Round|Patrick+Hand|Lato:300,400,700,300italic,400italic,700italic"
      rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Sniglet:800" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Fredoka+One&effect=3d|3d-float" rel="stylesheet"
      type="text/css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

<!-- Styles -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">
<link rel="stylesheet" href="{{ url_for('static', filename='css/defaults.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/custom.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='css/nav.css') }}">

cou_site/templates/_common/navbar.html
<nav class="navbar navbar-default" role="navigation" id="nav-header">
    <div class="container{{ '-fluid' if fluid }}">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('core_pages._index') }}">
                <span class="hidden-sm hidden-md">Children of </span>
                <img src="{{ url_for('static', filename='img/logo/cou_ur.svg') }}" height="100%" width="auto" alt="Ur">
            </a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
                {% for page in pages %}
                    <li class="{{ 'active' if is_active_page(page) }}">
                        <a href="{{ page.url }}">{{ page.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="https://childrenofur.com/game/">Play</a></li>
                {% if logged_in %}
                    <li id="logincontrol-loggedin" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span id="loggedin-username">{{ logged_in_username }}</span>
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a id="loggedin-profilelink" href="/players/{{ logged_in_username }}">
                                    <i class="fas fa-fw fa-user"></i> My Profile
                                </a>
                            </li>
                            <li>
                                <a href="{{ url_for('auth.logout_api') }}">
                                    <i class="fas fa-fw fa-sign-out-alt"></i> Log Out
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li id="logincontrol-loggedout">
                        <a href="{{ url_for('core_pages._login') }}"><i class="fas fa-sign-in-alt"></i> Log In</a>
                    </li>
                {% endif %}
                <li id="social-fa-links" class="hidden-sm">
                    <a title="Children of Ur on Facebook" href="https://www.facebook.com/childrenofur">
                        <i class="fab fa-fw fa-facebook"></i>
                    </a>
                    <a title="@ChildrenOfUr on Twitter" href="https://twitter.com/childrenofur">
                        <i class="fab fa-fw fa-twitter"></i>
                    </a>
                    <a title="Children of Ur Code on GitLab" href="https://gitlab.com/ChildrenOfUr">
                        <i class="fab fa-fw fa-gitlab"></i>
                    </a>
                    <a title="Email publicrelations@childrenofur.com" href="mailto:publicrelations@childrenofur.com">
                        <i class="fas fa-fw fa-envelope"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

cou_site/templates/_common/pagination.html
{% if num_pages > 0 %}
    <ul class="pagination">
        {% if page > 1 %}
            <li>
                <a href="?page={{ page - 1 }}">&laquo;</a>
            </li>
        {% endif %}
        {% for i in range(1, num_pages + 1) %}
            <li class="{{ 'active' if i == page }}">
                <a href="?page={{ i }}">{{ i }}</a>
            </li>
        {% endfor %}
        {% if page < num_pages %}
            <li>
                <a href="?page={{ page + 1 }}">&raquo;</a>
            </li>
        {% endif %}
    </ul>
{% endif %}

cou_site/templates/_common/preview.html
<div class="panel panel-default">
    <div class="panel-heading">
        <a href="{{ reply.url if showing_reply else post.url }}">
            {% if showing_reply %}
                <b>Replying to</b>
            {% endif %}
            {{ post.title }}</a>
    </div>
    <div class="panel-body">
        {% if showing_reply %}
            {{ reply.preview }}
        {% else %}
            {{ post.preview }}
        {% endif %}
    </div>
    <ul class="list-group">
        {% if not showing_reply %}
            <li class="list-group-item">
                <i class="fas fa-fw fa-user"></i>
                Posted by <a href="{{ post.user.profile_url }}">{{ post.user.username }}</a>
            </li>
        {% endif %}

        <li class="list-group-item">
            <i class="fas fa-fw fa-clock"></i>
            <span title="{{ post.created }}">{{ post.created_ago }}</span>
        </li>

        {% if show_category %}
            <li class="list-group-item list-group-item-{{ post.category.color }}">
                <i class="fas fa-fw fa-folder"></i>
                <a href="{{ post.category.url }}">{{ post.category.name }}</a>
            </li>
        {% endif %}

        {% if not showing_reply %}
            <li class="list-group-item">
                <i class="fas fa-fw fa-comments"></i>
                {{ post.num_replies }}
                {{ "reply" if post.num_replies == 1 else "replies" }}
            </li>
            {% if not post.is_blog_post %}
                <li class="list-group-item">
                    <i class="fas fa-fw fa-bell"></i>
                    {{ post.num_watchers }} subscribed
                </li>
            {% endif %}
        {% endif %}
    </ul>
</div>

cou_site/templates/_common/randbg.html
<style>
    .randbg {
        background: url({{ url_for('static', filename='img/backgrounds/' + rand_bg()) }}) top center;
        background-size: cover;
    }
</style>

cou_site/templates/_common/tinymce.html
<script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=v4a98qb9jxiy841dm73twzz8s8dkp1gcitzbzoknla9gkhk8"></script>
<script src="{{ url_for('static', filename='js/editor.js') }}"></script>