cou_site/models/category.py
from sqlalchemy.ext.hybrid import hybrid_property

from cou_site.controllers.util.navigation import pages
from cou_site.models import db

PAGE = "category"
POST_LIST_LIMIT = 20


class Category:
    _num_posts = None

    @staticmethod
    def find(cat_id: str):
        for cat in FORUM_CATEGORIES + BLOG_CATEGORIES:
            if cat.cat_id == cat_id:
                return cat

        return None

    def __init__(
        self,
        name: str,
        description: str,
        color: str = "default",
        cat_id: str = str(),
        hidden: bool = False,
    ):
        self.name = name
        self.description = description
        self.color = color
        self.cat_id = cat_id if cat_id else name.replace(" ", "").lower()
        self.hidden = hidden
        self.voting_enabled = self.cat_id == "voting"

    @property
    def url(self):
        page = "blog" if self.is_blog_category else "forums"
        return f"{pages[page].url}/{PAGE}/{self.cat_id}"

    @property
    def num_posts(self) -> int:
        if not self._num_posts:
            from .post import Post

            self._num_posts = (
                db.session.query(Post).filter(Post.category_id == self.cat_id).count()
            )

        return self._num_posts

    @hybrid_property
    def is_blog_category(self):
        return self in BLOG_CATEGORIES


FORUM_CATEGORIES = [
    Category(
        "Announcements & Events",
        "Talking about game updates as well as planning in-game and real-world events.",
        color="info",
        cat_id="anev",
    ),
    Category(
        "General",
        (
            "Whatever you want it to be "
            "(as long as it's at least tangentially related to the game)."
        ),
        color="primary",
    ),
    Category(
        "Ideas", "What do you think we should put in the game next?", color="success"
    ),
    Category(
        "Bugs",
        (
            "Discussion of possible bugs found in the game. "
            "Note that this is not for official bug reports."
        ),
        color="danger",
    ),
    Category(
        "Off Topic",
        "A place to talk about anything not related to the game.",
        color="warning",
    ),
    Category(
        "Voting",
        (
            "Replies to posts here can be voted up or down "
            "and will be ranked by the score."
        ),
    ),
    Category("Comments", "Used for comments on blog posts.", hidden=True),
]

BLOG_CATEGORIES = [
    Category("Announcements", str()),
    Category("Behind the Scenes", "Development progress", cat_id="bts"),
    Category("Community Participation", "We need you!", cat_id="crowdsourcing"),
    Category("Game Updates", "New features and new bugs", cat_id="updates"),
    Category("Questions", "Answers to FAQs"),
    Category("Uncategorized", str()),
]

cou_site/controllers/__init__.py
from flask import Blueprint, render_template, abort, redirect, url_for
from sqlalchemy.orm.exc import NoResultFound

from cou_site.controllers.team import developers
from cou_site.models.post import Post


core_pages = Blueprint("core_pages", __name__)


@core_pages.route("/")
def _index():
    latest_post = (
        Post.query.filter(Post.is_blog_post)
        .order_by(Post.created.desc())
        .limit(1)
        .one()
    )
    return render_template("index.html", latest_post=latest_post)


@core_pages.route("/about")
def _about():
    return render_template("about.html", team=developers)


@core_pages.route("/about/features")
def _features():
    return render_template("features.html")


@core_pages.route("/fine-print")
def _fine_print():
    return render_template("fine_print.html")


@core_pages.route("/help")
def _help():
    return render_template("help.html")


@core_pages.route("/login")
def _login():
    return render_template("login.html")


@core_pages.route("/edit/<post_id>")
def edit_post(post_id):
    if not str.isdigit(post_id):
        return abort(404)

    try:
        post = Post.query.filter(Post.entry_id == post_id).one()
    except NoResultFound:
        return abort(404)

    return render_template("edit.html", mode="post", entry=post, category=post.category)

cou_site/controllers/forums.py
from math import ceil

from flask import Blueprint, render_template, abort, redirect, request
from sqlalchemy import and_, or_, func
from sqlalchemy.orm.exc import NoResultFound

from cou_site.controllers import edit_post as edit_generic_post
from cou_site.models.post import Post, PAGE as THREAD_PATH
from cou_site.models.reply import Reply
from cou_site.models.category import (
    Category,
    FORUM_CATEGORIES,
    PAGE as CATEGORY_PATH,
    POST_LIST_LIMIT,
)


forums = Blueprint("forums", __name__, url_prefix="/forums")


@forums.route("/")
def _index():
    return render_template("forums/index.html", categories=FORUM_CATEGORIES)


@forums.route(f"/{CATEGORY_PATH}/<cat_id>")
def category(cat_id):
    """Show the threads posted in a given category."""
    # Check category
    cat = Category.find(cat_id)
    if not cat:
        return abort(404)

    # Default page number
    page = request.args.get("page", "1")
    if not page:
        return redirect(cat.url, code=301)

    # Check page number
    if not str.isdigit(page):
        return abort(404)

    page = int(page)
    num_pages = max(ceil(cat.num_posts / POST_LIST_LIMIT), 1)

    # Page number out of bounds
    if page > num_pages:
        return abort(404)

    posts = (
        Post.query.order_by(Post.created.desc())
        .filter(Post.category_id == cat.cat_id)
        .limit(POST_LIST_LIMIT)
        .offset(POST_LIST_LIMIT * (page - 1))
        .all()
    )

    return render_template(
        "forums/category.html",
        category=cat,
        posts=posts,
        page=page,
        num_pages=num_pages,
    )


@forums.route(f"/{THREAD_PATH}/<post_id>")
def thread(post_id):
    """Show a post and its replies."""
    if not str.isdigit(post_id):
        return abort(404)

    try:
        post = Post.query.filter(Post.entry_id == post_id).one()
    except NoResultFound:
        return abort(404)

    if post.is_blog_post:
        return abort(404)

    return render_template("forums/thread.html", post=post)


@forums.route(f"/post/new")
def new_post():
    cat_id = request.args.get("category")
    if not cat_id:
        return abort(400)

    cat = Category.find(cat_id)
    if not cat or cat.is_blog_category:
        return abort(400)

    return render_template("edit.html", mode="post", entry=None, category=cat)


@forums.route(f"/edit/post")
def edit_post():
    post_id = request.args.get("id")

    if not post_id:
        return abort(400)

    return edit_generic_post(post_id)


@forums.route(f"/edit/reply")
def edit_reply():
    reply_id = request.args.get("id")

    if not reply_id:
        return abort(400)

    if not str.isdigit(reply_id):
        return abort(400)

    try:
        reply = Reply.query.filter(Reply.entry_id == reply_id).one()
    except NoResultFound:
        return abort(404)
    return render_template("edit.html", mode="reply", entry=reply)


@forums.route(f"/search")
def search():
    """Show the matching posts for a search query."""
    query = request.args.get("q", type=str, default=str()).lower()
    posts = []

    if query:
        posts = (
            Post.query.filter(
                and_(
                    Post.category_id != "comments",
                    or_(
                        func.lower(Post.title).contains(query),
                        func.lower(Post.content).contains(query),
                    ),
                )
            )
            .order_by(Post.created.desc())
            .all()
        )

    return render_template("forums/search.html", query=query, posts=posts)

cou_site/templates/forums/category.html
<!doctype html>
<html lang="en">
<head>
    {% include "_common/head.html" %}
    <title>{{ category.name }} | CoU Forums</title>
</head>
<body>
{% include "_common/navbar.html" %}

<div class="container">
    <!-- Header -->
    <div class="row">
        <div class="{{ 'col-sm-9' if logged_in else 'col-md-12' }}">
            <div class="page-header">
                <h1>
                    <small>Posts in</small>
                    {{ category.name }}
                </h1>
                <h4>{{ category.description }}</h4>
            </div>
        </div>
        {% if logged_in %}
        <div class="col-sm-3">
            <br>
            <a href="{{ url_for('forums.new_post') }}?category={{ category.cat_id }}" class="btn btn-success btn-block btn-lg">
                <i class="fas fa-edit"></i>
                Create post
            </a>
        </div>
        {% endif %}
    </div>

    <!-- Posts -->
    <div class="grid row">
        {% if num_pages == 0 %}
        <div class="col-md-12">
            <div class="alert alert-warning">There are no posts in this category.</div>
        </div>
        {% endif %}

        {% for post in posts %}
        <div class="grid-item col-sm-6 col-md-4 col-lg-3">
            {% include "_common/preview.html" %}
        </div>
        {% endfor %}
    </div>

    <!-- Pagination -->
    <div class="row">
        <div class="col-md-12 text-center">
            <hr>
            {% include "_common/pagination.html" %}
        </div>
    </div>
</div>

{% include "_common/foot.html" %}
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script src="{{ url_for('static', filename='js/masonry.js') }}"></script>
</body>
</html>

cou_site/templates/forums/index.html
<!doctype html>
<html lang="en">
<head>
    {% include "_common/head.html" %}
    <title>CoU Forums</title>
</head>
<body>
{% include "_common/navbar.html" %}

<div class="container">
    <div class="row" id="categories">
        <div class="col-sm-12">
            <div class="page-header">
                <h2>Forums Search</h2>
            </div>
            <form action="/forums/search" method="get">
                <div class="input-group input-group-lg">
                    <input name="q" class="form-control" type="search" required>
                    <span class="input-group-btn">
                        <button class="btn btn-info" type="submit">
                            <i class="fas fa-search"></i> Go
                        </button>
                    </span>
                </div>
            </form>
        </div>

        <div class="col-md-12">
            &nbsp;
        </div>

        <div class="col-sm-12">
            <!-- Category listing -->
            <div class="page-header">
                <h2>Forum Categories</h2>
            </div>
            <div class="list-group">
                {% for category in categories if not category.hidden %}
                    <a href="{{ category.url }}" class="list-group-item list-group-item-action">
                        <span class="badge">{{ category.num_posts }} posts</span>
                        <h4 class="list-group-item-heading">{{ category.name }}</h4>
                        <p class="list-group-item-text">{{ category.description }}</p>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% include "_common/foot.html" %}
</body>
</html>

cou_site/templates/forums/search.html
<!doctype html>
<html lang="en">
<head>
    {% include "_common/head.html" %}
    <title>Search for "{{ query }}" | CoU Forums</title>
</head>
<body>
{% include "_common/navbar.html" %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1>Search results for <b>{{ query }}</b></h1>
            </div>
        </div>
    </div>
    <div class="grid row">
        {% set show_category = True %}
        {% for post in posts %}
        <div class="grid-item col-sm-6 col-md-4 col-lg-3">
            {% include "_common/preview.html" %}
        </div>
        {% endfor %}
    </div>
</div>

{% include "_common/foot.html" %}
<script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
<script src="{{ url_for('static', filename='js/masonry.js') }}"></script>
</body>
</html>

cou_site/templates/forums/thread.html
<!doctype html>
<html lang="en">
<head>
    {% include "_common/head.html" %}
    <title>{{ post.title }} | {{ post.category.name }} | CoU Forums</title>
</head>
<body>
{% include "_common/navbar.html" %}

<div class="container">
    <!-- Post -->
    <div class="row">
        {% if not logged_in and post.category.voting_enabled %}
        <div class="col-md-12">
            <div class="alert alert-info">
                If you want to vote on replies to this thread, you need to
                <a href="{{ url_for('core_pages._login') }}" class="alert-link">log in</a>.
            </div>
        </div>
        {% endif %}
        <div class="col-md-12">
            <div class="page-header">
                <h2>{{ post.title }}</h2>
                <hr>
            </div>
        </div>
        <div class="col-md-12">
            <div class="media" data-post-id="{{ post.entry_id }}">
                <div class="media-left avatar-head text-center">
                    <a href="{{ post.user.profile_url }}">
                        <img class="mr-3 media-object" src="{{ post.user.avatar_url }}"
                             alt="{{ post.user.username }}'s avatar">
                    </a>
                </div>
                <div class="media-body">
                    <div class="pull-right">
                        <button class="btn btn-default {{ 'active' if logged_in_user_id in post.watchers }}"
                                title="Reply Notifications" onclick="toggleSubscription(this)"
                                data-watch-post-id="{{ post.entry_id }}">
                            <i class="fas fa-fw fa-bell"></i>
                            <span class="count">{{ post.watchers | count }}</span>
                        </button>
                        {% if post.user_id == logged_in_user_id %}
                        <a href="{{ post.edit_url }}" class="btn btn-info" title="Edit Post">
                            <i class="fas fa-fw fa-edit"></i>
                        </a>
                        <button class="btn btn-danger" title="Delete Post" onclick="deletePost(this)"
                                data-delete-post-id="{{ post.entry_id }}">
                            <i class="fas fa-fw fa-trash"></i>
                        </button>
                        {% endif %}
                    </div>
                    <h4 class="media-heading">
                        <a href="{{ post.user.profile_url }}">{{ post.user.username }}</a>
                        posted in <a href="{{ post.category.url }}">{{ post.category.name }}</a>
                        <span title="{{ post.created }}">{{ post.created_ago }}</span>
                        {% if post.was_edited %}
                        (edited <span title="{{ post.edited }}">{{ post.edited_ago }}</span>)
                        {% endif %}
                    </h4>
                    <br>
                    {{ post.content | safe }}
                    <hr>

                    <!-- Replies -->
                    {%
                    for reply in post.replies | sort(
                    attribute=("score" if post.category.voting_enabled else "created"),
                    reverse=post.category.voting_enabled)
                    %}
                    <div class="media reply" data-reply-id="{{ reply.entry_id }}" id="reply-{{ reply.entry_id }}">
                        <div class="media-left avatar-head text-center">
                            <a href="{{ reply.user.profile_url }}">
                                <img class="mr-3 media-object" src="{{ reply.user.avatar_url }}"
                                     alt="{{ reply.user.username }}'s avatar">
                            </a>
                        </div>
                        <div class="media-body">
                            <div class="pull-right">
                                <!-- Editing -->
                                {% if reply.user_id == logged_in_user_id %}
                                <p>
                                    <a href="{{ reply.edit_url }}" class="btn btn-info" title="Edit Reply">
                                        <i class="fas fa-fw fa-edit"></i>
                                    </a>
                                    <button class="btn btn-danger"
                                            title="Delete Reply" data-delete-reply-id="{{ reply.entry_id }}">
                                        <i class="fas fa-fw fa-trash"></i>
                                    </button>
                                </p>
                                {% endif %}

                                <!-- Voting -->
                                {% if post.category.voting_enabled %}
                                {% if logged_in and reply.user_id != logged_in_user_id %}
                                <p class="text-center">
                                    <button class="btn btn-success {{ 'active' if logged_in_user_id in reply.upvoters }}"
                                            data-vote="up" data-loading-text="…">
                                        <i class="fas fa-fw fa-thumbs-up"></i>
                                    </button>
                                </p>
                                <p class="text-center reply-score" data-reply-id="{{ reply.entry_id }}">
                                    {{ reply.score }}
                                </p>
                                <p class="text-center">
                                    <button class="btn btn-warning {{ 'active' if logged_in_user_id in reply.downvoters }}"
                                            data-vote="down" data-loading-text="…">
                                        <i class="fas fa-fw fa-thumbs-down"></i>
                                    </button>
                                </p>
                                {% else %}
                                <p class="text-center reply-score lead " data-reply-id="{{ reply.entry_id }}">
                                    <b>{{ reply.score }}</b> pt{{ "s" if reply.score != 1 and reply.score != -1 }}
                                </p>
                                {% endif %}
                                {% endif %}
                            </div>

                            <h4 class="media-heading">
                                <a href="{{ reply.user.profile_url }}">{{ reply.user.username }}</a>
                                replied
                                <span title="{{ reply.created }}">{{ reply.created_ago }}</span>
                                {% if reply.was_edited %}
                                (edited <span title="{{ reply.edited }}">{{ reply.edited_ago }})</span>
                                {% endif %}
                            </h4>
                            <br>
                            {{ reply.content | safe }}
                        </div>
                        <hr>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <!-- Reply form -->
    <div class="row">
        <div class="col-md-12">
            <h2>
                <label for="reply-editor">
                    Reply
                </label>
            </h2>
            {% if logged_in %}
            <div class="alert alert-info visible-xs">
                You may need to tap the <i class="fas fa-book-open"></i> button to open the editor.
            </div>
            <textarea id="reply-editor" required></textarea>
            {% else %}
            <div class="alert alert-info">
                If you want to reply to this thread, you need to <a href="/login" class="alert-link">log in</a>.
            </div>
            {% endif %}
        </div>
    </div>

    <!-- Navigation -->
    <div class="row">
        <br>
        <div class="col-xs-6">
            {% if logged_in %}
            <button class="btn btn-success" onclick="submitNewReply(this)" data-loading-text="Submitting...">
                <i class="fas fa-save"></i>
                Submit Reply
            </button>
            {% endif %}
        </div>
        <div class="col-xs-6 text-right">
            <a href="#" class="btn btn-primary">
                <i class="fas fa-arrow-up"></i>
                Back to top
            </a>
        </div>
    </div>
</div>

{% include "_common/foot.html" %}

<script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=v4a98qb9jxiy841dm73twzz8s8dkp1gcitzbzoknla9gkhk8"></script>
<script src="{{ url_for('static', filename='js/editor.js') }}"></script>
<script src="{{ url_for('static', filename='js/thread.js') }}"></script>
</body>
</html>