cou_site/controllers/__init__.py
from flask import Blueprint, render_template, abort, redirect, url_for
from sqlalchemy.orm.exc import NoResultFound

from cou_site.controllers.team import developers
from cou_site.models.post import Post


core_pages = Blueprint("core_pages", __name__)


@core_pages.route("/")
def _index():
    latest_post = (
        Post.query.filter(Post.is_blog_post)
        .order_by(Post.created.desc())
        .limit(1)
        .one()
    )
    return render_template("index.html", latest_post=latest_post)


@core_pages.route("/about")
def _about():
    return render_template("about.html", team=developers)


@core_pages.route("/about/features")
def _features():
    return render_template("features.html")


@core_pages.route("/fine-print")
def _fine_print():
    return render_template("fine_print.html")


@core_pages.route("/help")
def _help():
    return render_template("help.html")


@core_pages.route("/login")
def _login():
    return render_template("login.html")


@core_pages.route("/edit/<post_id>")
def edit_post(post_id):
    if not str.isdigit(post_id):
        return abort(404)

    try:
        post = Post.query.filter(Post.entry_id == post_id).one()
    except NoResultFound:
        return abort(404)

    return render_template("edit.html", mode="post", entry=post, category=post.category)

cou_site/controllers/guides.py
from datetime import datetime, timedelta

from flask import Blueprint, render_template
from sqlalchemy import and_

from cou_site.models.user import User


guides = Blueprint("guides", __name__, url_prefix="/guides")


@guides.route("/")
def _index():
    return render_template("guides.html", guides=list_guides())


def list_guides() -> list:
    """
    Return a list of guides who have logged in within the last year
    sorted with the most recently logged in first.
    """
    year_ago = datetime.utcnow() - timedelta(days=365)

    active_guides = User.query.filter(
        and_(
            User.elevation == "guide",
            User.last_login is not None,
            User.last_login > year_ago,
        )
    ).order_by(User.last_login.desc())

    return active_guides

cou_site/controllers/team.py
from collections import namedtuple

from flask import Blueprint, redirect, render_template, abort

from cou_site.controllers.util.navigation import pages
from cou_site.models.user import User

team = Blueprint("team", __name__, url_prefix="/team")

TeamMember = namedtuple("TeamMember", "slug name role bio cou_username glitch_id")

developers = [
    TeamMember(
        slug="andy",
        name="Andy Castille",
        role="Tinkerer",
        bio=(
            "He joined the CoU project in early 2014 after watching "
            "the development process. He contributes code "
            "(like the recipes feature), helped write the forums software, "
            "and manage the website and profile pages."
        ),
        cou_username="Klikini",
        glitch_id="PHVRFUTFUQA2TAH",
    ),
    TeamMember(
        slug="robert",
        name="Robert McDermot",
        role="Regional Programming Liaison",
        cou_username="Thaderator",
        glitch_id="PUV8J99156F2N8M",
        bio=(
            'A coder monkey who brings a new meaning to the term "programmer art", '
            "Robert joined the project in the fall of 2013. "
            "A stout believer that Egyptian Brackets suck and has been known to "
            "use Pokemon Exception Handling one to many times. "
            '<a href="http://blog.codinghorror.com/new-programming-jargon/">'
            "Jargon Reference</a>"
        ),
    ),
    TeamMember(
        slug="develle",
        name="Laura Montgomery",
        role="Graphic Designer",
        bio=(
            "I'm here to help optimize graphics, missing assets, "
            "and help revive missing/broken/dead streets. Etc."
        ),
        glitch_id="PUV91K2AAKG2S00",
        cou_username="Elle Lament",
    ),
    TeamMember(
        slug="paul",
        name="Paul VanKeuren",
        role="Head Imagineer",
        bio=(
            "A philosophy student making games. "
            "He started the CoU Glitch revival project in 2013, "
            "shortly after the game closed and before the assets were released "
            "into the public domain. "
            "His contributions include design choices and code."
        ),
        cou_username="Paal",
        glitch_id="PIFSJMGTUI63Q6F",
    ),
    TeamMember(
        slug="courtney",
        name="Courtney B Reid",
        cou_username="Lead",
        role="Develop-o-nator and Designifier",
        bio=(
            "Joined the team in 2013, and has since added code, art, "
            "design, and good karma to the project. Her patron Giant is Lem."
        ),
        glitch_id="PHVBB509QK42GQD",
    ),
    TeamMember(
        slug="lizzard",
        name="Liz Henry",
        role="Dev",
        bio=None,
        cou_username="lizzard",
        glitch_id=None,
    ),
    TeamMember(
        slug="katharine",
        name="Katharine Gibeau",
        glitch_id="PIFPNVKDTL63AO3",
        role="Twitter Wizard",
        bio="Manages CoU’s social media platforms and communicates with the players "
        "and public. When stuff is happening at CoU, she will be sure to let you "
        "know about it.",
        cou_username=str(),
    ),
    TeamMember(
        slug="pixley",
        name="Craig Cottingham",
        glitch_id="PHFPPJFJTVC2RK0",
        bio=None,
        cou_username="Pixley",
        role=None,
    ),
]


def get_dev(slug: str) -> TeamMember or None:
    found = [m for m in developers if m.slug == slug]

    if found:
        return found[0]
    else:
        return None


@team.route("/")
def _index():
    return redirect(pages["about"].url + "#team")


@team.route("/<slug>")
def _developer(slug: str):
    dev = get_dev(slug)

    if not dev:
        return abort(404)

    return render_template(
        "team_member.html",
        member=dev,
        profile_url=f"{pages['profiles'].url}/{dev.cou_username}",
        avatar_url=User.make_avatar_url(dev.cou_username),
    )

cou_site/templates/about.html
<!doctype html>
<html lang="en">
<head>
    {% include "_common/head.html" %}
    <title>About Children of Ur</title>
</head>
<body>
{% include "_common/navbar.html" %}

<div class="container">
    <div class="page-header">
        <h1 class="text-center">
            About CoU
        </h1>
    </div>
    <div class="row">
        <div class="col-md-12">
            <img src="{{ url_for('static', filename='img/npc/flamingo_flamingo.png') }}" class="pull-right"
                 alt="Flamingo Flamingo">
            <h2>We're making the world a little bright Ur.</h2>
            <p>
                Children of Ur is a 2D browser-based game in the early stages of development. It's a social
                multiplayer
                set in a big world where you play with your friends. We're building the game from the ground up, and
                you
                may encounter bugs while playing. Updates are posted weekly, if not daily.
            </p>
            <p>
                There's a lot more to come! Watch out for more updates in the near future, and check out our
                <a href="{{ url_for('core_pages._features') }}">current features</a>.
            </p>

            <div class="clearfix"></div>

            <img src="{{ url_for('static', filename='img/npc/rube.png') }}" class="pull-left pl-sp" alt="Rube">
            <h2>We stand on the shoulders of Giants.</h2>
            This game is a spinoff to Glitch™ the Game, which ran during 2009-2012, but eventually closed due to
            lack of funding. The developers of the game, Tiny Speck Inc., released much of the code and art assets
            from the game into public domain. As such, we are recreating the world of Glitch, and have plans to
            expand the original universe.

            <div class="clearfix"></div>

            <img src="{{ url_for('static', filename='img/npc/frog.png') }}" class="pull-right" alt="Frog">
            <h2>Designed in the spirit of the open web.</h2>
            <p>
                So just how are we making the game? We are building the game in open technologies, very much in the
                spirit of the web. Most of the code so far is written in Dart, a newer web programming language
                created by Google. All of the technologies we are using are based in HTML5, a web standard promoting
                accessibility and mobility. In doing so, we can create the code for free, you can play in almost any
                browser (including many mobile browsers), and you'll never need to download anything to play.
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="page-header section-divider">
                <h2 id="team">
                    <a href="#team"><i class="fas fa-bookmark"></i></a>
                    Meet the Team
                </h2>
            </div>
        </div>
    </div>

    <!-- Team -->
    <div class="row">
        <!-- List -->
        {% for member in team %}
            <div class="col-md-4">
                <a href="{{ url_for('team._developer', slug=member.slug) }}" class="thumbnail thumbnail-wh thumbnail-pt thumbnail-bg"
                   style="background-image: url({{ url_for('static', filename='img/team/' + member.slug + '_bg.jpg') }});">
                    <img src="{{ url_for('static', filename='img/team/' + member.slug + '.png') }}"
                         alt="{{ member.name }}'s avatar">
                    <div class="caption">
                        <h2 class="text-center">{{ member.name }}</h2>
                    </div>
                </a>
            </div>
        {% endfor %}

        <!-- Recruit -->
        <div class="col-md-4">
            <div class="thumbnail thumbnail-wh thumbnail-pt">
                <div class="caption text-center row">
                    <div class="col-md-10 col-md-offset-1">
                        <h2>Want to help out?</h2>
                        <p>
                            Knowledge of <a href="https://dartlang.org">Dart</a> (or a willingness to learn, we can
                            help) as well as a basic understanding of HTML and CSS is suggested to help out with the
                            game itself, but you can also help with art &amp; assets (Inkscape), website design
                            (HTML, CSS), etc.
                        </p>
                        <p>
                            Email us at <a href="mailto:publicrelations@childrenofur.com">publicrelations@childrenofur.com</a>
                            if you're interested.
                        </p>
                        <hr>
                        <p>
                            Don't know how to program? Continue playing and reporting bugs, or
                            <a href="{{ url_for('guides._index') }}">become a guide</a>!
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% include "_common/foot.html" %}
</body>
</html>

cou_site/templates/edit.html
<!doctype html>
<html lang="en">
<head>
    {% include "_common/head.html" %}
    <title>{{ ("Editing " if entry else "Creating ") + mode }} | CoU Forums</title>
    <meta name="X-CoU-Blogging" content="{{ mode == "post" and category.is_blog_category }}">
</head>
<body>
{% include "_common/navbar.html" %}

<div class="container">
    <!-- Reply form -->
    <div class="row">
        <div class="col-md-12">
            <h2>
                <label for="editor">
                    {% if entry %}
                    Editing {{ entry.title if mode == "post" else "reply" }}
                    {% else %}
                    New Post
                    {% endif %}
                </label>
                {% if mode == "post" %}
                <small>in {{ category.name }}</small>
                {% elif mode == "reply" %}
                <small>to "{{ entry.post.title }}"</small>
                {% endif %}
            </h2>
            {% if mode == "post" %}
            <input type="text" class="form-control" id="entry-title" placeholder="Post title" value="{{ entry.title | trim }}">
            <br>
            <input type="hidden" id="entry-category" value="{{ category.cat_id }}">
            {% endif %}
            <div class="alert alert-info visible-xs">
                You may need to tap the <i class="fas fa-book-open"></i> button to open the editor.
            </div>
            <textarea class="form-control" id="editor" required>{{ entry.content }}</textarea>
        </div>
    </div>

    <!-- Navigation -->
    <div class="row">
        <br>
        <div class="col-md-12">
            <button class="btn btn-success" onclick="submitStandalone(this)"
                    data-loading-text="Submitting, please wait..."
                    data-entry-id="{{ entry.entry_id }}" data-entry-type="{{ mode }}">
                <i class="fas fa-upload"></i>
                Publish {{ "changes" if entry }}
            </button>

            {% if mode == "post" and category.is_blog_category %}
                <button class="btn btn-warning" onclick="submitStandalone(this)"
                        data-loading-text="Saving, please wait..."
                        data-entry-id="{{ entry.entry_id }}" data-entry-type="{{ mode }}" data-draft="true">
                    <i class="fas fa-save"></i>
                    Save draft
                </button>
            {% endif %}

            {% if mode == "post" %}
                <button class="btn btn-danger" onclick="deletePost(this)"
                        data-delete-post-id="{{ entry.entry_id }}">
                    <i class="fas fa-trash"></i>
                    Delete post
                </button>
            {% endif %}
        </div>
    </div>
</div>

{% include "_common/foot.html" %}
<script src="https://cloud.tinymce.com/5/tinymce.min.js?apiKey=v4a98qb9jxiy841dm73twzz8s8dkp1gcitzbzoknla9gkhk8"></script>
<script src="{{ url_for('static', filename='js/editor.js') }}"></script>
{% if mode == "post" %}
    <script src="{{ url_for('static', filename='js/thread.js') }}"></script>
{% endif %}
</body>
</html>

cou_site/templates/error.html
<!doctype html>
<html lang="en">
<head>
    {% include "_common/head.html" %}
    {% include "_common/randbg.html" %}
    <title>Error {{ error_code }} | Children of Ur</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/error.css') }}">
</head>
<body class="randbg">
{% include "_common/navbar.html" %}

<div class="container main-container">
    <div class="row">
        &nbsp;
    </div>
    <div class="row">
        <div class="col-sm-6">
            <h1 class="center-block graphic" style="font-size: 64px;">Error {{ error.code if error.code else 500 }}</h1>
            <h2 class="center-block graphic">{{ error }}</h2>
        </div>
        <div class="col-sm-6">
            <div class="err-cubimal"></div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12 text-center">
            <a href="{{ url_for('core_pages._index') }}" class="btn btn-primary btn-lg">Go to Homepage</a>
        </div>
    </div>
</div>

{% include "_common/foot.html" %}
</body>
</html>

cou_site/templates/features.html
<!doctype html>
<html lang="en">
<head>
    {% include "_common/head.html" %}
    <title>Children of Ur Features</title>
</head>
<body>
{% include "_common/navbar.html" %}

<div class="container">
    <div class="page-header">
        <h1 class="text-center">
            Features
        </h1>
    </div>
    <div class="page-header section-divider">
        <img src="{{ url_for('static', filename='img/npc/deimaginator.png') }}" class="pull-right" alt="Deimaginator">
        <h2 id="issues">
            <a href="#issues"><i class="fas fa-bookmark"></i></a>
            Known Issues
        </h2>
    </div>
    <p>
        Issues and feature requests are maintained on our
        <a href="https://github.com/ChildrenOfUr/cou-issues/issues" target="_blank">GitHub issues page</a>.
    </p>
    <div class="page-header section-divider clearfix">
        <h2 id="features">
            <a href="#features"><i class="fas fa-bookmark"></i></a>
            Releases
        </h2>
    </div>
    <p>
        The game is currently in <strong>Alpha</strong>, which means there's still a lot of bugs and features that
        haven't yet made it into the game. If you want to report a bug or request a new feature, check out our
        <a href="{{ url_for('core_pages._help') }}#report" target="_blank">reporting info</a> or
        <a href="https://github.com/ChildrenOfUr/cou-issues/issues">bug reports</a>.
    </p>
    <div class="page-header section-divider">
        <img src="{{ url_for('static', filename='img/npc/greeterbot.png') }}" class="pull-right" alt="Greeterbot">
        <h2 id="community">
            <a href="#community"><i class="fas fa-bookmark"></i></a>
            Community
        </h2>
    </div>
    <p>
        Our community (you guys!) is what makes this game so special. Our goal is to make Children of Ur a more
        community-driven game than Glitch, taking in more user input and help with development, to make a game you
        want to play.
    </p>
    <p>
        We had great success with the <a href="https://childrenofur.com/mapfiller/">MapFiller</a> and the entity
        phrase suggestions, leading us to believe that the community is more involved already. If you have any
        messages for us, create an issue on GitHub, email us, or contact us on social media.
    </p>
</div>

{% include "_common/foot.html" %}
</body>
</html>

cou_site/templates/fine_print.html
<!doctype html>
<html lang="en">
<head>
    {% include "_common/head.html" %}
    <title>Fine Print | Children of Ur</title>
</head>
<body>
{% include "_common/navbar.html" %}

<div class="container">
    <div class="page-header">
        <h1 class="text-center">Fine Print</h1>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p class="text-danger text-center">Voiding the Terms of Service or Community Guidelines will result in a
                ban of varying length, so read carefully.</p>


        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="page-header section-divider">
                <h1>Community Guidelines</h1>
            </div>
        </div>
    </div>
    <h2>Act with Respect Towards Others</h2>
    <ul>
        <li>
            Absolutely no personal attacks or hateful speech directed at others’ gender, sexual orientation,
            religious beliefs, ethnic background or anything else you should have the good sense not to hate on.
        </li>
        <li>
            Public areas in the game deserve the same sort of decorum, tact and consideration that public areas in
            your neighborhood do: excessive obscenity, vulgarity, or other kinds of generally offensive behavior are
            not welcome.
        </li>
        <li>
            No griefing or harassing other players. It’s not fun, or funny. Really. If you are in the game for the
            purpose of pissing other people off, you can’t play.
        </li>
    </ul>
    <h2>Make Children of Ur a Welcoming Place</h2>
    It’s hard to create and sustain great communities on the Internet. Children of Ur is a great community and
    sustaining it will take effort, from you as well as from us.
    <ul>
        <li>
            Public areas are public, so treat them as a shared resource.
        </li>
        <li>
            Though we may compete or have rivalries and conflicts inside the game world, we are all playing
            together. Competition in the game does not preclude offering help and hospitality to other players.
        </li>
        <li>
            Avoid assuming bad intentions in other players: some of them will think differently than you; or English
            might not be their first language; or their kid will have spilled a glass of milk on the cat a second
            ago; or they might not understand the particular nuances with which you play. Or... who knows? A
            willingness to forgive will go a long way, especially when directed towards new players who might not
            yet have fully learned what effects their actions have on others.
        </li>
    </ul>
    <h2>There is no "right way" to play</h2>
    <ul>
        <li>
            Creating new gameplay by adopting roles (good or bad) is good. A little mischief can be welcome (as
            long, of course, as it is within the guidelines articulated here and our Terms of Service).
        </li>
        <li>
            Vigilante action against players who are, in your opinion, playing "incorrectly" can be griefing too and
            it is not allowed. If you see abuse in the game, you should report it. But calling out another player in
            the forums or public channels and organizing people to bully them is itself a kind of harassment and
            will be moderated as such.
        </li>
    </ul>
    <h2>Play Fair</h2>
    In Children of Ur, the journey matters far more than the destination. This game is not about just winning,
    leveling up, or amassing the most currants.
    <ul>
        <li>
            Using bots, mules, or other hacks to gain significant and unfair advantage in the game is not allowed.
        </li>
        <li>
            Multiple accounts controlled by one person playing at the same time is not allowed.
        </li>
        <li>
            Duping or deceiving other players into doing things which benefit you at their expense is not allowed.
        </li>
    </ul>
    <h2>Don’t Just Speak Up, but Listen Too</h2>
    Active participation is important to building the game together, but listening to other perspectives is
    important too:
    <ul>
        <li>
            If people don’t respond to what you have to say, move on. Flooding public areas with the same idea is
            not OK.
        </li>
        <li>
            We may moderate public areas of conversation (forums, global chat, live help, and other areas of the
            site) when it feels that the conversation is being hidden behind people shouting.
        </li>
        <li>
            Use appropriate channels for your conversation:
            <ul>
                <li>
                    Each of the forums and public channels is for a specific use — respect our guidelines.
                </li>
                <li>
                    Some conversation is just for friends or personal chats, keep this conversation out of public
                    areas and in IMs, Mail, in Groups or other channels of communication.
                </li>
            </ul>
        </li>
        <li>
            Hectoring, badgering and continuing to talk to people after they’ve expressed that they don’t want to
            talk to you is just another kind of harassment: don’t do it.
        </li>
    </ul>
    <h2>The Bottom Line</h2>
    <p>
        Though we have a moderated community, the ideal is a community that is mostly self-regulating. But keep in
        mind that no one has a right to play and access to the game is at the sole discretion of the game’s
        administrators (the CoU development team). If you can't abide by the guidelines above, you can’t play.
        It is our job to keep CoU a safe and welcoming place. We might not catch everything that goes wrong,
        but we'll try our hardest, with your help.
    </p>
    <div class="page-header section-divider">
        <h1>Terms of Service</h1>
    </div>
    <p>
        Any participation in this game or site will constitute acceptance of this agreement. If you do not agree to
        abide by the above, please do not use this site.
    </p>
    <div class="page-header section-divider">
        <h1>Do you agree?</h1>
    </div>
    <p>
        While accepting to follow these terms is optional, you cannot play the game if you decline.
    </p>
    <div class="row">
        <form>
            <div class="col-md-3 col-xs-6">
                <button type="submit" class="btn btn-success btn-lg btn-block">Accept</button>
            </div>
            <div class="col-md-3 col-xs-6">
                <button type="submit" class="btn btn-danger btn-lg btn-block">Decline</button>
            </div>
        </form>
    </div>
</div>

{% include "_common/foot.html" %}
</body>
</html>

cou_site/templates/index.html
<!doctype html>
<html lang="en">
<head>
    {% include "_common/head.html" %}
    <title>Children of Ur</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/flipcountdown.css') }}">
    {% include "_common/randbg.html" %}
</head>
<body>
{% include "_common/navbar.html" %}

<div class="jumbotron randbg" id="jumbotron-home">
    <div class="container">
        <div class="row graphic">
            <div class="col-md-8 col-md-offset-3">
                <h1>Children of</h1>
                <img src="{{ url_for('static', filename='img/logo/ur_logo_shadow.png') }}" alt="Ur" width="auto"
                     height="200px">
            </div>
        </div>
        <div class="row graphic">
            <div class="col-md-12">
                <h1 class="text-center">A Game of Giant Imagination</h1>
                <h2 class="text-center">Join us for early access!</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <a href="https://childrenofur.com/game/" class="btn btn-lg button-xl btn-success center-block">
                    Play Now</a>
            </div>
        </div>
    </div>
    <div class="row graphic">
        <div class="col-md-10 col-md-offset-1">
            <h3 class="text-center">
                From the blog:
                <a href="{{ latest_post.url }}"><strong>{{ latest_post.title }}</strong></a>
            </h3>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8 col-sm-8 col-md-offset-1">
            <p class="text-justify semi-lead">
                Children of Ur is a massively-multiplayer game, playable in the browser and chock full of fun.
                The game is set in the vast, imaginative world of Ur, dreamt up by eleven Giants and shaped by
                players
                all over the globe.
            </p>
            <p class="text-justify semi-lead">
                The game is a spinoff of <a href="http://glitchthegame.com" target="_blank">Glitch™ the Game</a>,
                featuring new areas, updated storylines, and a whole host of new things to come. It is currently in
                early development and is available to play now. Still interested?
                <a href="{{ url_for('core_pages._about') }}">Learn More <i class="fas fa-arrow-right"></i></a>
            </p>
        </div>
        <div class="col-md-2 col-sm-3 hidden-xs">
            <br class="visible-sm">
            <img src="{{ url_for('static', filename='img/npc/hk02041.png') }}" class="img-responsive" alt="Heli Kitty">
        </div>
    </div>

    <!-- Stats flip display -->
    <div class="row" id="countStats">
        <div class="col-md-12" id="countContainer">
            <span id="flipcounter"></span>
            <span id="countText"></span>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12"></div>
    </div>

    <!-- Call to action NPCs -->
    <div class="row" id="cta-imgs">
        <div class="col-md-3 col-sm-3 hidden-xs cta-slice-div"
             style="background-image: url({{ url_for('static', filename='img/cta/cta_bg3_1.png') }});"></div>
        <div class="col-md-3 col-sm-3 hidden-xs cta-slice-div"
             style="background-image: url({{ url_for('static', filename='img/cta/cta_bg3_2.png') }});"></div>
        <div class="col-md-3 col-sm-3 hidden-xs cta-slice-div"
             style="background-image: url({{ url_for('static', filename='img/cta/cta_bg3_3.png') }});"></div>
        <div class="col-md-3 col-sm-3 col-xs-12 cta-slice-div"
             style="background-image: url({{ url_for('static', filename='img/cta/cta_bg3_4.png') }});"></div>
        <div class="col-md-12 text-center">
            <a href="https://childrenofur.com/game/" id="cta-slice-cta" class="btn btn-lg button-xl btn-danger">
                Try the Game
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p class="text-right">
                <a href="https://www.netlify.com">
                    <img src="https://www.netlify.com/img/global/badges/netlify-color-bg.svg" alt="Netlify.">
                </a>
            </p>
        </div>
    </div>
</div>

{% include "_common/foot.html" %}
<script src="{{ url_for('static', filename='js/jquery.flipcountdown.js') }}"></script>
<script src="{{ url_for('static', filename='js/entitycount.js') }}"></script>
</body>
</html>

cou_site/templates/login.html
<!doctype html>
<html lang="en">
<head>
    {% include "_common/head.html" %}
    <title>Log in to Children of Ur</title>
</head>
<body>
{% include "_common/navbar.html" %}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="page-header">
                <h1>Log In</h1>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <cou-login></cou-login>
        </div>
        <div class="col-md-6">
            <h2>Registration</h2>
            <p>
                If you've never logged in before, that's OK. You may either register by putting in an email address and
                password and clicking the registration link we send you. OR you can use one of the social logins
                provided. If you decide to switch login methods in the future, no worries. Your account is tied to you
                via your email address. As long as your social login emails match or you register that email address
                with us, you're good to go.
            </p>

        </div>
    </div>
</div>

{% include "_common/foot.html" %}
<script src="https://www.gstatic.com/firebasejs/5.5.2/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/5.5.2/firebase-auth.js"></script>
<script src="{{ url_for('static', filename='js/login.js') }}"></script>
<script defer src="{{ url_for('static', filename='js/login.dart.js') }}"></script>
</body>
</html>